model_type: KGPL_COT
neighbor_sample_size: 32
dropout_rate: 0.5
emb_dim: 64
n_iter: 1
plabel:
  lp_depth: 5
  par: 16
  chunk_size: 3000
  pl_pn: 0.001
  neg_pn: 0.1
optimize:
  iter_per_epoch: 20
  lr: 5e-3
  batch_size: 9999